runtime: python39
instance_class: F1
service: palm2-slack-chatbot
automatic_scaling:
  target_cpu_utilization: 0.90
  min_instances: 1
  max_instances: 1
entrypoint: uvicorn app:api --reload --port 8080